packages:
  - "packages/*"
  - "apps/*/*"
allowBuilds:
  electron: set this to true or false
  sharp: set this to true or false
onlyBuiltDependencies:
  - electron
  - esbuild
  - mongodb-memory-server
  - sharp
